/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Employee" CASCADE;

CREATE TABLE "Employee" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL);

